import = [ "~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml", "~/.local/share/omakub/defaults/alacritty.toml" ]

[window]
opacity = 0.95
padding.x = 30
padding.y = 30
dimensions.columns = 90
dimensions.lines = 25

[font]
size = 10
